# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

collections:
    algos:
        output: true
    cs61a:
        output: true

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew M. Zhang
email: me@andrewmzhang.com
description: > # this means to ignore newlines until "baseurl:"
  Placeholder description
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blog.andrewmzhang.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: andrewmzhang
github_username: andrewmzhang
repository: andrewmzhang/mysite

# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-hacker
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
